// Code generated by go-enum-encoding; DO NOT EDIT.

package measurement

import (
	"encoding/json/v2"
	"errors"
	"fmt"
	"math/rand"
	"slices"
	"testing"
)

func ExampleMeasureType_MarshalText() {
	for _, v := range []MeasureType{MeasureTypeUndefined, MeasureTypeMass, MeasureTypeVolume} {
		b, _ := v.MarshalText()
		fmt.Printf("%s ", string(b))
	}
	// Output:  mass volume
}

func ExampleMeasureType_UnmarshalText() {
	for _, s := range []string{"", "mass", "volume"} {
		var v MeasureType
		if err := (&v).UnmarshalText([]byte(s)); err != nil {
			fmt.Println(err)
		}
	}
}

func TestMeasureType_MarshalText_UnmarshalText(t *testing.T) {
	for _, v := range []MeasureType{MeasureTypeUndefined, MeasureTypeMass, MeasureTypeVolume} {
		b, err := v.MarshalText()
		if err != nil {
			t.Errorf("cannot encode: %s", err)
		}

		var d MeasureType
		if err := (&d).UnmarshalText(b); err != nil {
			t.Errorf("cannot decode: %s", err)
		}

		if d != v {
			t.Errorf("exp(%v) != got(%v)", v, d)
		}
	}

	t.Run("when unknown value, then error", func(t *testing.T) {
		s := `something`
		var v MeasureType
		err := (&v).UnmarshalText([]byte(s))
		if err == nil {
			t.Error("must be error")
		}
		if !errors.Is(err, ErrUnknownMeasureType) {
			t.Error("wrong error", err)
		}
	})
}

func TestMeasureType_JSON(t *testing.T) {
	type V struct {
		Values []MeasureType `json:"values"`
	}

	values := []MeasureType{MeasureTypeUndefined, MeasureTypeMass, MeasureTypeVolume}

	var v V
	s := `{"values":["","mass","volume"]}`
	json.Unmarshal([]byte(s), &v)

	if len(v.Values) != len(values) {
		t.Errorf("cannot decode: %d", len(v.Values))
	}
	if !slices.Equal(v.Values, values) {
		t.Errorf("wrong decoded: %v", v.Values)
	}

	b, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("cannot encode: %s", err)
	}
	if string(b) != s {
		t.Errorf("wrong encoded: %s != %s", string(b), s)
	}

	t.Run("when unknown value, then error", func(t *testing.T) {
		s := `{"values":["something"]}`
		var v V
		err := json.Unmarshal([]byte(s), &v)
		if err == nil {
			t.Error("must be error")
		}
		if !errors.Is(err, ErrUnknownMeasureType) {
			t.Error("wrong error", err)
		}
	})
}

func BenchmarkMeasureType_UnmarshalText(b *testing.B) {
	vb := seq_bytes_MeasureType[rand.Intn(len(seq_bytes_MeasureType))]

	var x MeasureType

	for b.Loop() {
		_ = x.UnmarshalText(vb)
	}
}

func BenchmarkMeasureType_AppendText(b *testing.B) {
	bb := make([]byte, 10, 1000)

	vs := []MeasureType{MeasureTypeUndefined, MeasureTypeMass, MeasureTypeVolume}
	v := vs[rand.Intn(len(vs))]

	for b.Loop() {
		_, _ = v.AppendText(bb)
	}
}

func BenchmarkMeasureType_MarshalText(b *testing.B) {
	vs := []MeasureType{MeasureTypeUndefined, MeasureTypeMass, MeasureTypeVolume}
	v := vs[rand.Intn(len(vs))]

	for b.Loop() {
		_, _ = v.MarshalText()
	}
}

func TestMeasureType_String(t *testing.T) {
	values := []MeasureType{MeasureTypeUndefined, MeasureTypeMass, MeasureTypeVolume}
	tags := []string{"", "mass", "volume"}

	for i := range values {
		if s := values[i].String(); s != tags[i] {
			t.Error(s, tags[i])
		}
	}
}

func BenchmarkMeasureType_String(b *testing.B) {
	vs := []MeasureType{MeasureTypeUndefined, MeasureTypeMass, MeasureTypeVolume}
	v := vs[rand.Intn(len(vs))]

	for b.Loop() {
		_ = v.String()
	}
}
