// Code generated by go-enum-encoding; DO NOT EDIT.

package measurement

import "errors"

var ErrUnknownMeasureType = errors.New("unknown MeasureType")

func (s *MeasureType) UnmarshalText(text []byte) error {
	switch string(text) {
	case "":
		*s = MeasureTypeUndefined
	case "mass":
		*s = MeasureTypeMass
	case "volume":
		*s = MeasureTypeVolume
	default:
		return ErrUnknownMeasureType
	}
	return nil
}

var seq_bytes_MeasureType = [...][]byte{[]byte(""), []byte("mass"), []byte("volume")}

func (s MeasureType) MarshalText() ([]byte, error) { return s.AppendText(nil) }

func (s MeasureType) AppendText(b []byte) ([]byte, error) {
	switch s {
	case MeasureTypeUndefined:
		return append(b, seq_bytes_MeasureType[0]...), nil
	case MeasureTypeMass:
		return append(b, seq_bytes_MeasureType[1]...), nil
	case MeasureTypeVolume:
		return append(b, seq_bytes_MeasureType[2]...), nil
	default:
		return nil, ErrUnknownMeasureType
	}
}

var seq_string_MeasureType = [...]string{"", "mass", "volume"}

func (s MeasureType) String() string {
	switch s {
	case MeasureTypeUndefined:
		return seq_string_MeasureType[0]
	case MeasureTypeMass:
		return seq_string_MeasureType[1]
	case MeasureTypeVolume:
		return seq_string_MeasureType[2]
	default:
		return ""
	}
}
