// Code generated by go-enum-encoding; DO NOT EDIT.

package measurement

import "errors"

var ErrUnknownUnitMass = errors.New("unknown UnitMass")

func (s *UnitMass) UnmarshalText(text []byte) error {
	switch string(text) {
	case "":
		*s = UnitMassUnknown
	case "pg":
		*s = UnitPicograms
	case "ng":
		*s = UnitNanograms
	case "mcg":
		*s = UnitMicrograms
	case "mg":
		*s = UnitMilligrams
	case "cg":
		*s = UnitCentigrams
	case "dg":
		*s = UnitDecigrams
	case "g":
		*s = UnitGrams
	case "kg":
		*s = UnitKilograms
	case "oz":
		*s = UnitOunces
	case "lb":
		*s = UnitPounds
	case "st":
		*s = UnitStones
	case "ton":
		*s = UnitMetricTons
	case "sst":
		*s = UnitShortTons
	case "ct":
		*s = UnitCarats
	case "ozt":
		*s = UnitOuncesTroy
	case "slug":
		*s = UnitSlugs
	default:
		return ErrUnknownUnitMass
	}
	return nil
}

var seq_bytes_UnitMass = [...][]byte{[]byte(""), []byte("pg"), []byte("ng"), []byte("mcg"), []byte("mg"), []byte("cg"), []byte("dg"), []byte("g"), []byte("kg"), []byte("oz"), []byte("lb"), []byte("st"), []byte("ton"), []byte("sst"), []byte("ct"), []byte("ozt"), []byte("slug")}

func (s UnitMass) MarshalText() ([]byte, error) { return s.AppendText(nil) }

func (s UnitMass) AppendText(b []byte) ([]byte, error) {
	switch s {
	case UnitMassUnknown:
		return append(b, seq_bytes_UnitMass[0]...), nil
	case UnitPicograms:
		return append(b, seq_bytes_UnitMass[1]...), nil
	case UnitNanograms:
		return append(b, seq_bytes_UnitMass[2]...), nil
	case UnitMicrograms:
		return append(b, seq_bytes_UnitMass[3]...), nil
	case UnitMilligrams:
		return append(b, seq_bytes_UnitMass[4]...), nil
	case UnitCentigrams:
		return append(b, seq_bytes_UnitMass[5]...), nil
	case UnitDecigrams:
		return append(b, seq_bytes_UnitMass[6]...), nil
	case UnitGrams:
		return append(b, seq_bytes_UnitMass[7]...), nil
	case UnitKilograms:
		return append(b, seq_bytes_UnitMass[8]...), nil
	case UnitOunces:
		return append(b, seq_bytes_UnitMass[9]...), nil
	case UnitPounds:
		return append(b, seq_bytes_UnitMass[10]...), nil
	case UnitStones:
		return append(b, seq_bytes_UnitMass[11]...), nil
	case UnitMetricTons:
		return append(b, seq_bytes_UnitMass[12]...), nil
	case UnitShortTons:
		return append(b, seq_bytes_UnitMass[13]...), nil
	case UnitCarats:
		return append(b, seq_bytes_UnitMass[14]...), nil
	case UnitOuncesTroy:
		return append(b, seq_bytes_UnitMass[15]...), nil
	case UnitSlugs:
		return append(b, seq_bytes_UnitMass[16]...), nil
	default:
		return nil, ErrUnknownUnitMass
	}
}

var seq_string_UnitMass = [...]string{"", "pg", "ng", "mcg", "mg", "cg", "dg", "g", "kg", "oz", "lb", "st", "ton", "sst", "ct", "ozt", "slug"}

func (s UnitMass) String() string {
	switch s {
	case UnitMassUnknown:
		return seq_string_UnitMass[0]
	case UnitPicograms:
		return seq_string_UnitMass[1]
	case UnitNanograms:
		return seq_string_UnitMass[2]
	case UnitMicrograms:
		return seq_string_UnitMass[3]
	case UnitMilligrams:
		return seq_string_UnitMass[4]
	case UnitCentigrams:
		return seq_string_UnitMass[5]
	case UnitDecigrams:
		return seq_string_UnitMass[6]
	case UnitGrams:
		return seq_string_UnitMass[7]
	case UnitKilograms:
		return seq_string_UnitMass[8]
	case UnitOunces:
		return seq_string_UnitMass[9]
	case UnitPounds:
		return seq_string_UnitMass[10]
	case UnitStones:
		return seq_string_UnitMass[11]
	case UnitMetricTons:
		return seq_string_UnitMass[12]
	case UnitShortTons:
		return seq_string_UnitMass[13]
	case UnitCarats:
		return seq_string_UnitMass[14]
	case UnitOuncesTroy:
		return seq_string_UnitMass[15]
	case UnitSlugs:
		return seq_string_UnitMass[16]
	default:
		return ""
	}
}
