// Code generated by go-enum-encoding; DO NOT EDIT.

package measurement

import (
	"encoding/json/v2"
	"errors"
	"fmt"
	"math/rand"
	"slices"
	"testing"
)

func ExampleUnitVolume_MarshalText() {
	for _, v := range []UnitVolume{UnitVolumeUnknown, UnitMilliLiters, UnitCentiLiters, UnitDeciLiters, UnitLiters, UnitKiloLiters, UnitMegaLiters, UnitCubicMilliMeters, UnitCubicCentiMeters, UnitCubicDeciMeters, UnitCubicFeet, UnitCubicInches, UnitCubicMeters, UnitCubicKiloMeters, UnitCubicMiles, UnitCubicYards, UnitBushels, UnitCups, UnitFluidOunces, UnitGallons, UnitPints, UnitQuarts, UnitTablespoons, UnitTeaspoons, UnitImperialFluidOunces, UnitImperialGallons, UnitImperialGills, UnitImperialPints, UnitImperialQuarts, UnitImperialTablespoons, UnitImperialTeaspoons} {
		b, _ := v.MarshalText()
		fmt.Printf("%s ", string(b))
	}
	// Output:  ml cl dl l kl Ml mm3 cm3 dm3 ft3 in3 m3 km3 mi3 yd3 bu cup floz gal pt qt tbsp tsp impfloz impgal impgil imppt impqt imptbsp imptsp
}

func ExampleUnitVolume_UnmarshalText() {
	for _, s := range []string{"", "ml", "cl", "dl", "l", "kl", "Ml", "mm3", "cm3", "dm3", "ft3", "in3", "m3", "km3", "mi3", "yd3", "bu", "cup", "floz", "gal", "pt", "qt", "tbsp", "tsp", "impfloz", "impgal", "impgil", "imppt", "impqt", "imptbsp", "imptsp"} {
		var v UnitVolume
		if err := (&v).UnmarshalText([]byte(s)); err != nil {
			fmt.Println(err)
		}
	}
}

func TestUnitVolume_MarshalText_UnmarshalText(t *testing.T) {
	for _, v := range []UnitVolume{UnitVolumeUnknown, UnitMilliLiters, UnitCentiLiters, UnitDeciLiters, UnitLiters, UnitKiloLiters, UnitMegaLiters, UnitCubicMilliMeters, UnitCubicCentiMeters, UnitCubicDeciMeters, UnitCubicFeet, UnitCubicInches, UnitCubicMeters, UnitCubicKiloMeters, UnitCubicMiles, UnitCubicYards, UnitBushels, UnitCups, UnitFluidOunces, UnitGallons, UnitPints, UnitQuarts, UnitTablespoons, UnitTeaspoons, UnitImperialFluidOunces, UnitImperialGallons, UnitImperialGills, UnitImperialPints, UnitImperialQuarts, UnitImperialTablespoons, UnitImperialTeaspoons} {
		b, err := v.MarshalText()
		if err != nil {
			t.Errorf("cannot encode: %s", err)
		}

		var d UnitVolume
		if err := (&d).UnmarshalText(b); err != nil {
			t.Errorf("cannot decode: %s", err)
		}

		if d != v {
			t.Errorf("exp(%v) != got(%v)", v, d)
		}
	}

	t.Run("when unknown value, then error", func(t *testing.T) {
		s := `something`
		var v UnitVolume
		err := (&v).UnmarshalText([]byte(s))
		if err == nil {
			t.Error("must be error")
		}
		if !errors.Is(err, ErrUnknownUnitVolume) {
			t.Error("wrong error", err)
		}
	})
}

func TestUnitVolume_JSON(t *testing.T) {
	type V struct {
		Values []UnitVolume `json:"values"`
	}

	values := []UnitVolume{UnitVolumeUnknown, UnitMilliLiters, UnitCentiLiters, UnitDeciLiters, UnitLiters, UnitKiloLiters, UnitMegaLiters, UnitCubicMilliMeters, UnitCubicCentiMeters, UnitCubicDeciMeters, UnitCubicFeet, UnitCubicInches, UnitCubicMeters, UnitCubicKiloMeters, UnitCubicMiles, UnitCubicYards, UnitBushels, UnitCups, UnitFluidOunces, UnitGallons, UnitPints, UnitQuarts, UnitTablespoons, UnitTeaspoons, UnitImperialFluidOunces, UnitImperialGallons, UnitImperialGills, UnitImperialPints, UnitImperialQuarts, UnitImperialTablespoons, UnitImperialTeaspoons}

	var v V
	s := `{"values":["","ml","cl","dl","l","kl","Ml","mm3","cm3","dm3","ft3","in3","m3","km3","mi3","yd3","bu","cup","floz","gal","pt","qt","tbsp","tsp","impfloz","impgal","impgil","imppt","impqt","imptbsp","imptsp"]}`
	json.Unmarshal([]byte(s), &v)

	if len(v.Values) != len(values) {
		t.Errorf("cannot decode: %d", len(v.Values))
	}
	if !slices.Equal(v.Values, values) {
		t.Errorf("wrong decoded: %v", v.Values)
	}

	b, err := json.Marshal(v)
	if err != nil {
		t.Fatalf("cannot encode: %s", err)
	}
	if string(b) != s {
		t.Errorf("wrong encoded: %s != %s", string(b), s)
	}

	t.Run("when unknown value, then error", func(t *testing.T) {
		s := `{"values":["something"]}`
		var v V
		err := json.Unmarshal([]byte(s), &v)
		if err == nil {
			t.Error("must be error")
		}
		if !errors.Is(err, ErrUnknownUnitVolume) {
			t.Error("wrong error", err)
		}
	})
}

func BenchmarkUnitVolume_UnmarshalText(b *testing.B) {
	vb := seq_bytes_UnitVolume[rand.Intn(len(seq_bytes_UnitVolume))]

	var x UnitVolume

	for b.Loop() {
		_ = x.UnmarshalText(vb)
	}
}

func BenchmarkUnitVolume_AppendText(b *testing.B) {
	bb := make([]byte, 10, 1000)

	vs := []UnitVolume{UnitVolumeUnknown, UnitMilliLiters, UnitCentiLiters, UnitDeciLiters, UnitLiters, UnitKiloLiters, UnitMegaLiters, UnitCubicMilliMeters, UnitCubicCentiMeters, UnitCubicDeciMeters, UnitCubicFeet, UnitCubicInches, UnitCubicMeters, UnitCubicKiloMeters, UnitCubicMiles, UnitCubicYards, UnitBushels, UnitCups, UnitFluidOunces, UnitGallons, UnitPints, UnitQuarts, UnitTablespoons, UnitTeaspoons, UnitImperialFluidOunces, UnitImperialGallons, UnitImperialGills, UnitImperialPints, UnitImperialQuarts, UnitImperialTablespoons, UnitImperialTeaspoons}
	v := vs[rand.Intn(len(vs))]

	for b.Loop() {
		_, _ = v.AppendText(bb)
	}
}

func BenchmarkUnitVolume_MarshalText(b *testing.B) {
	vs := []UnitVolume{UnitVolumeUnknown, UnitMilliLiters, UnitCentiLiters, UnitDeciLiters, UnitLiters, UnitKiloLiters, UnitMegaLiters, UnitCubicMilliMeters, UnitCubicCentiMeters, UnitCubicDeciMeters, UnitCubicFeet, UnitCubicInches, UnitCubicMeters, UnitCubicKiloMeters, UnitCubicMiles, UnitCubicYards, UnitBushels, UnitCups, UnitFluidOunces, UnitGallons, UnitPints, UnitQuarts, UnitTablespoons, UnitTeaspoons, UnitImperialFluidOunces, UnitImperialGallons, UnitImperialGills, UnitImperialPints, UnitImperialQuarts, UnitImperialTablespoons, UnitImperialTeaspoons}
	v := vs[rand.Intn(len(vs))]

	for b.Loop() {
		_, _ = v.MarshalText()
	}
}

func TestUnitVolume_String(t *testing.T) {
	values := []UnitVolume{UnitVolumeUnknown, UnitMilliLiters, UnitCentiLiters, UnitDeciLiters, UnitLiters, UnitKiloLiters, UnitMegaLiters, UnitCubicMilliMeters, UnitCubicCentiMeters, UnitCubicDeciMeters, UnitCubicFeet, UnitCubicInches, UnitCubicMeters, UnitCubicKiloMeters, UnitCubicMiles, UnitCubicYards, UnitBushels, UnitCups, UnitFluidOunces, UnitGallons, UnitPints, UnitQuarts, UnitTablespoons, UnitTeaspoons, UnitImperialFluidOunces, UnitImperialGallons, UnitImperialGills, UnitImperialPints, UnitImperialQuarts, UnitImperialTablespoons, UnitImperialTeaspoons}
	tags := []string{"", "ml", "cl", "dl", "l", "kl", "Ml", "mm3", "cm3", "dm3", "ft3", "in3", "m3", "km3", "mi3", "yd3", "bu", "cup", "floz", "gal", "pt", "qt", "tbsp", "tsp", "impfloz", "impgal", "impgil", "imppt", "impqt", "imptbsp", "imptsp"}

	for i := range values {
		if s := values[i].String(); s != tags[i] {
			t.Error(s, tags[i])
		}
	}
}

func BenchmarkUnitVolume_String(b *testing.B) {
	vs := []UnitVolume{UnitVolumeUnknown, UnitMilliLiters, UnitCentiLiters, UnitDeciLiters, UnitLiters, UnitKiloLiters, UnitMegaLiters, UnitCubicMilliMeters, UnitCubicCentiMeters, UnitCubicDeciMeters, UnitCubicFeet, UnitCubicInches, UnitCubicMeters, UnitCubicKiloMeters, UnitCubicMiles, UnitCubicYards, UnitBushels, UnitCups, UnitFluidOunces, UnitGallons, UnitPints, UnitQuarts, UnitTablespoons, UnitTeaspoons, UnitImperialFluidOunces, UnitImperialGallons, UnitImperialGills, UnitImperialPints, UnitImperialQuarts, UnitImperialTablespoons, UnitImperialTeaspoons}
	v := vs[rand.Intn(len(vs))]

	for b.Loop() {
		_ = v.String()
	}
}
