// Code generated by go-enum-encoding; DO NOT EDIT.

package measurement

import "errors"

var ErrUnknownUnitVolume = errors.New("unknown UnitVolume")

func (s *UnitVolume) UnmarshalText(text []byte) error {
	switch string(text) {
	case "":
		*s = UnitVolumeUnknown
	case "ml":
		*s = UnitMilliLiters
	case "cl":
		*s = UnitCentiLiters
	case "dl":
		*s = UnitDeciLiters
	case "l":
		*s = UnitLiters
	case "kl":
		*s = UnitKiloLiters
	case "Ml":
		*s = UnitMegaLiters
	case "mm3":
		*s = UnitCubicMilliMeters
	case "cm3":
		*s = UnitCubicCentiMeters
	case "dm3":
		*s = UnitCubicDeciMeters
	case "ft3":
		*s = UnitCubicFeet
	case "in3":
		*s = UnitCubicInches
	case "m3":
		*s = UnitCubicMeters
	case "km3":
		*s = UnitCubicKiloMeters
	case "mi3":
		*s = UnitCubicMiles
	case "yd3":
		*s = UnitCubicYards
	case "bu":
		*s = UnitBushels
	case "cup":
		*s = UnitCups
	case "floz":
		*s = UnitFluidOunces
	case "gal":
		*s = UnitGallons
	case "pt":
		*s = UnitPints
	case "qt":
		*s = UnitQuarts
	case "tbsp":
		*s = UnitTablespoons
	case "tsp":
		*s = UnitTeaspoons
	case "impfloz":
		*s = UnitImperialFluidOunces
	case "impgal":
		*s = UnitImperialGallons
	case "impgil":
		*s = UnitImperialGills
	case "imppt":
		*s = UnitImperialPints
	case "impqt":
		*s = UnitImperialQuarts
	case "imptbsp":
		*s = UnitImperialTablespoons
	case "imptsp":
		*s = UnitImperialTeaspoons
	default:
		return ErrUnknownUnitVolume
	}
	return nil
}

var seq_bytes_UnitVolume = [...][]byte{[]byte(""), []byte("ml"), []byte("cl"), []byte("dl"), []byte("l"), []byte("kl"), []byte("Ml"), []byte("mm3"), []byte("cm3"), []byte("dm3"), []byte("ft3"), []byte("in3"), []byte("m3"), []byte("km3"), []byte("mi3"), []byte("yd3"), []byte("bu"), []byte("cup"), []byte("floz"), []byte("gal"), []byte("pt"), []byte("qt"), []byte("tbsp"), []byte("tsp"), []byte("impfloz"), []byte("impgal"), []byte("impgil"), []byte("imppt"), []byte("impqt"), []byte("imptbsp"), []byte("imptsp")}

func (s UnitVolume) MarshalText() ([]byte, error) { return s.AppendText(nil) }

func (s UnitVolume) AppendText(b []byte) ([]byte, error) {
	switch s {
	case UnitVolumeUnknown:
		return append(b, seq_bytes_UnitVolume[0]...), nil
	case UnitMilliLiters:
		return append(b, seq_bytes_UnitVolume[1]...), nil
	case UnitCentiLiters:
		return append(b, seq_bytes_UnitVolume[2]...), nil
	case UnitDeciLiters:
		return append(b, seq_bytes_UnitVolume[3]...), nil
	case UnitLiters:
		return append(b, seq_bytes_UnitVolume[4]...), nil
	case UnitKiloLiters:
		return append(b, seq_bytes_UnitVolume[5]...), nil
	case UnitMegaLiters:
		return append(b, seq_bytes_UnitVolume[6]...), nil
	case UnitCubicMilliMeters:
		return append(b, seq_bytes_UnitVolume[7]...), nil
	case UnitCubicCentiMeters:
		return append(b, seq_bytes_UnitVolume[8]...), nil
	case UnitCubicDeciMeters:
		return append(b, seq_bytes_UnitVolume[9]...), nil
	case UnitCubicFeet:
		return append(b, seq_bytes_UnitVolume[10]...), nil
	case UnitCubicInches:
		return append(b, seq_bytes_UnitVolume[11]...), nil
	case UnitCubicMeters:
		return append(b, seq_bytes_UnitVolume[12]...), nil
	case UnitCubicKiloMeters:
		return append(b, seq_bytes_UnitVolume[13]...), nil
	case UnitCubicMiles:
		return append(b, seq_bytes_UnitVolume[14]...), nil
	case UnitCubicYards:
		return append(b, seq_bytes_UnitVolume[15]...), nil
	case UnitBushels:
		return append(b, seq_bytes_UnitVolume[16]...), nil
	case UnitCups:
		return append(b, seq_bytes_UnitVolume[17]...), nil
	case UnitFluidOunces:
		return append(b, seq_bytes_UnitVolume[18]...), nil
	case UnitGallons:
		return append(b, seq_bytes_UnitVolume[19]...), nil
	case UnitPints:
		return append(b, seq_bytes_UnitVolume[20]...), nil
	case UnitQuarts:
		return append(b, seq_bytes_UnitVolume[21]...), nil
	case UnitTablespoons:
		return append(b, seq_bytes_UnitVolume[22]...), nil
	case UnitTeaspoons:
		return append(b, seq_bytes_UnitVolume[23]...), nil
	case UnitImperialFluidOunces:
		return append(b, seq_bytes_UnitVolume[24]...), nil
	case UnitImperialGallons:
		return append(b, seq_bytes_UnitVolume[25]...), nil
	case UnitImperialGills:
		return append(b, seq_bytes_UnitVolume[26]...), nil
	case UnitImperialPints:
		return append(b, seq_bytes_UnitVolume[27]...), nil
	case UnitImperialQuarts:
		return append(b, seq_bytes_UnitVolume[28]...), nil
	case UnitImperialTablespoons:
		return append(b, seq_bytes_UnitVolume[29]...), nil
	case UnitImperialTeaspoons:
		return append(b, seq_bytes_UnitVolume[30]...), nil
	default:
		return nil, ErrUnknownUnitVolume
	}
}

var seq_string_UnitVolume = [...]string{"", "ml", "cl", "dl", "l", "kl", "Ml", "mm3", "cm3", "dm3", "ft3", "in3", "m3", "km3", "mi3", "yd3", "bu", "cup", "floz", "gal", "pt", "qt", "tbsp", "tsp", "impfloz", "impgal", "impgil", "imppt", "impqt", "imptbsp", "imptsp"}

func (s UnitVolume) String() string {
	switch s {
	case UnitVolumeUnknown:
		return seq_string_UnitVolume[0]
	case UnitMilliLiters:
		return seq_string_UnitVolume[1]
	case UnitCentiLiters:
		return seq_string_UnitVolume[2]
	case UnitDeciLiters:
		return seq_string_UnitVolume[3]
	case UnitLiters:
		return seq_string_UnitVolume[4]
	case UnitKiloLiters:
		return seq_string_UnitVolume[5]
	case UnitMegaLiters:
		return seq_string_UnitVolume[6]
	case UnitCubicMilliMeters:
		return seq_string_UnitVolume[7]
	case UnitCubicCentiMeters:
		return seq_string_UnitVolume[8]
	case UnitCubicDeciMeters:
		return seq_string_UnitVolume[9]
	case UnitCubicFeet:
		return seq_string_UnitVolume[10]
	case UnitCubicInches:
		return seq_string_UnitVolume[11]
	case UnitCubicMeters:
		return seq_string_UnitVolume[12]
	case UnitCubicKiloMeters:
		return seq_string_UnitVolume[13]
	case UnitCubicMiles:
		return seq_string_UnitVolume[14]
	case UnitCubicYards:
		return seq_string_UnitVolume[15]
	case UnitBushels:
		return seq_string_UnitVolume[16]
	case UnitCups:
		return seq_string_UnitVolume[17]
	case UnitFluidOunces:
		return seq_string_UnitVolume[18]
	case UnitGallons:
		return seq_string_UnitVolume[19]
	case UnitPints:
		return seq_string_UnitVolume[20]
	case UnitQuarts:
		return seq_string_UnitVolume[21]
	case UnitTablespoons:
		return seq_string_UnitVolume[22]
	case UnitTeaspoons:
		return seq_string_UnitVolume[23]
	case UnitImperialFluidOunces:
		return seq_string_UnitVolume[24]
	case UnitImperialGallons:
		return seq_string_UnitVolume[25]
	case UnitImperialGills:
		return seq_string_UnitVolume[26]
	case UnitImperialPints:
		return seq_string_UnitVolume[27]
	case UnitImperialQuarts:
		return seq_string_UnitVolume[28]
	case UnitImperialTablespoons:
		return seq_string_UnitVolume[29]
	case UnitImperialTeaspoons:
		return seq_string_UnitVolume[30]
	default:
		return ""
	}
}
